In [8]:
import os, sys
sys.path.insert(0, "../")
import datetime
import gzip 
import pickle
import gc
import dolphindb.settings as keys
import warnings
import pandas as pd
pd.set_option("display.max_rows", 200)

from factor_cal.utils.tools import show_memory

In [9]:
base_path = "/data2/ddb_data"
print("Loading snap info")
show_memory("  before load_snap_info")
date_str = "20240219"
snap_filepath = os.path.join(base_path, 'ticker_' + date_str + '.pkl')

Loading snap info
  before load_snap_info 一共占用82.27MB

In [10]:
def read_pickle(filepath):
    with gzip.open(filepath, 'rb') as f:
        data = pickle.load(f)
    return data

In [11]:
data = read_pickle(snap_filepath)

In [12]:
result = {}
total = 0
error_num = 0
for date in pd.date_range("2024-02-07", periods=100):
    date = date.strftime("%Y%m%d")
    snap_filepath = os.path.join(base_path, 'ticker_' + date + '.pkl')
    if os.path.exists(snap_filepath):
        data = read_pickle(snap_filepath)
        show_memory(f"{date}:  after load_snap_info")
        result[date] = []
        data = data[(data['bid_size1'] < 0) | (data['ask_size1'] < 0)]
        result[date].append(data.shape[0])
        result[date].append(data['code'].unique().tolist())
        total += 1
        if data.shape[0] > 0:
            error_num += 1
        del data
        gc.collect()

print('total:', total, 'error_num:', error_num, 'portion:', error_num/total)

20240207:  after load_snap_info 一共占用5943.61MB
20240208:  after load_snap_info 一共占用6028.25MB
20240219:  after load_snap_info 一共占用5757.54MB
20240220:  after load_snap_info 一共占用5557.65MB
20240221:  after load_snap_info 一共占用5797.85MB
20240222:  after load_snap_info 一共占用5587.62MB
20240223:  after load_snap_info 一共占用5754.00MB
20240226:  after load_snap_info 一共占用5898.19MB
20240227:  after load_snap_info 一共占用5738.41MB
20240228:  after load_snap_info 一共占用6172.85MB
20240229:  after load_snap_info 一共占用5844.21MB
20240301:  after load_snap_info 一共占用5755.31MB
20240304:  after load_snap_info 一共占用5649.25MB
20240305:  after load_snap_info 一共占用5590.05MB
20240306:  after load_snap_info 一共占用5543.77MB
20240307:  after load_snap_info 一共占用5571.89MB
20240308:  after load_snap_info 一共占用5369.00MB
20240311:  after load_snap_info 一共占用5556.39MB
20240312:  after load_snap_info 一共占用5660.44MB
20240313:  after load_snap_info 一共占用5628.84MB
20240314:  after load_snap_info 一共占用5605.18MB
20240315:  after load_snap_info 一共占用5532.44MB
20240318:  after load_snap_info 一共占用5735.89MB
20240319:  after load_snap_info 一共占用5601.34MB
20240320:  after load_snap_info 一共占用5561.73MB
20240321:  after load_snap_info 一共占用5642.82MB
20240322:  after load_snap_info 一共占用5681.99MB
20240325:  after load_snap_info 一共占用5651.33MB
20240326:  after load_snap_info 一共占用5654.09MB
20240327:  after load_snap_info 一共占用5478.46MB
20240328:  after load_snap_info 一共占用5696.52MB
20240329:  after load_snap_info 一共占用5484.49MB
20240401:  after load_snap_info 一共占用5594.52MB
20240402:  after load_snap_info 一共占用5598.61MB
20240403:  after load_snap_info 一共占用5538.29MB
20240408:  after load_snap_info 一共占用5596.54MB
20240409:  after load_snap_info 一共占用5440.32MB
20240410:  after load_snap_info 一共占用5524.85MB
20240411:  after load_snap_info 一共占用5433.63MB
20240412:  after load_snap_info 一共占用5375.34MB
20240415:  after load_snap_info 一共占用5736.45MB
20240416:  after load_snap_info 一共占用5642.75MB
20240417:  after load_snap_info 一共占用5692.70MB
20240418:  after load_snap_info 一共占用5619.08MB
20240419:  after load_snap_info 一共占用5497.68MB
20240422:  after load_snap_info 一共占用5378.85MB
20240423:  after load_snap_info 一共占用5358.14MB
20240424:  after load_snap_info 一共占用5420.06MB
20240425:  after load_snap_info 一共占用5428.34MB
20240426:  after load_snap_info 一共占用5649.45MB
20240429:  after load_snap_info 一共占用5762.96MB
20240430:  after load_snap_info 一共占用5575.55MB
20240506:  after load_snap_info 一共占用5653.60MB
20240507:  after load_snap_info 一共占用5547.75MB
20240508:  after load_snap_info 一共占用5470.18MB
20240509:  after load_snap_info 一共占用5424.59MB
20240510:  after load_snap_info 一共占用5487.39MB
20240513:  after load_snap_info 一共占用5426.89MB
20240514:  after load_snap_info 一共占用5335.91MB
20240515:  after load_snap_info 一共占用5224.94MB
20240516:  after load_snap_info 一共占用5346.11MB
total: 61 error_num: 8 portion: 0.13114754098360656

In [14]:
import pickle
pickle.dump(result, open("pkl/snap_error_data.pkl", "wb"))

In [16]:
a = pickle.loads(open("pkl/snap_error_data.pkl", "rb").read())

In [26]:
df = pd.DataFrame({"error_date": "2023.02.20"}, index=[0])
df

   error_date
0  2023.02.20

In [29]:
df = None
for k, v in a.items():
    if (len(v[1]) > 0):
        df = pd.concat([df, pd.DataFrame({'error_date': k}, index=[0])], axis=0, ignore_index=True)

In [30]:
df.to_csv("pkl/snap_error_date.csv", index=True)

In [22]:
union_codes = None
for k, v in a.items():
    if union_codes is None:
        union_codes = set(v[1])
    else:
        union_codes.intersection(v[1])

differences = {}
for k, v in a.items():
    if len(set(v[1]) - union_codes) > 0:
        differences[k] = set(v[1]) - union_codes

In [23]:
for k, v in differences.items():
    print(k, len(v))

20240208 50
20240219 64
20240220 38
20240221 90
20240222 33
20240223 49
20240226 55

In [15]:
result.keys()

dict_keys(['20240207', '20240208', '20240219', '20240220', '20240221', '20240222', '20240223', '20240226', '20240227', '20240228', '20240229', '20240301', '20240304', '20240305', '20240306', '20240307', '20240308', '20240311', '20240312', '20240313', '20240314', '20240315', '20240318', '20240319', '20240320', '20240321', '20240322', '20240325', '20240326', '20240327', '20240328', '20240329', '20240401', '20240402', '20240403', '20240408', '20240409', '20240410', '20240411', '20240412', '20240415', '20240416', '20240417', '20240418', '20240419', '20240422', '20240423', '20240424', '20240425', '20240426', '20240429', '20240430', '20240506', '20240507', '20240508', '20240509', '20240510', '20240513', '20240514', '20240515', '20240516'])

In [20]:
len(union_codes), union_codes

(43,
 {'000005.SZ',
  '000030.SZ',
  '000035.SZ',
  '000503.SZ',
  '000565.SZ',
  '000795.SZ',
  '000801.SZ',
  '000829.SZ',
  '000837.SZ',
  '000972.SZ',
  '002036.SZ',
  '002057.SZ',
  '002092.SZ',
  '002099.SZ',
  '002123.SZ',
  '002173.SZ',
  '002212.SZ',
  '002217.SZ',
  '002219.SZ',
  '002245.SZ',
  '002325.SZ',
  '002375.SZ',
  '002414.SZ',
  '002527.SZ',
  '002621.SZ',
  '002654.SZ',
  '002673.SZ',
  '002689.SZ',
  '002724.SZ',
  '300067.SZ',
  '300432.SZ',
  '600010.SH',
  '600151.SH',
  '600157.SH',
  '600225.SH',
  '600351.SH',
  '600418.SH',
  '601288.SH',
  '601798.SH',
  '603135.SH',
  '603363.SH',
  '603555.SH',
  '603960.SH'})

In [22]:
data_filter = data[data['bid_size1'] < 0]

In [23]:
data_filter.shape[0]

50566

In [12]:
data_filter['code'].unique().tolist()

['600203.SH',
 '603660.SH',
 '600010.SH',
 '600491.SH',
 '601798.SH',
 '600490.SH',
 '600157.SH',
 '600172.SH',
 '601288.SH',
 '600351.SH',
 '601868.SH',
 '600622.SH',
 '601599.SH',
 '600844.SH',
 '002488.SZ',
 '002178.SZ',
 '300527.SZ',
 '000402.SZ',
 '002185.SZ',
 '002325.SZ',
 '002549.SZ',
 '002285.SZ',
 '002537.SZ',
 '002606.SZ',
 '000831.SZ',
 '002023.SZ',
 '002467.SZ',
 '002551.SZ',
 '000851.SZ',
 '002662.SZ',
 '000016.SZ',
 '002219.SZ',
 '300271.SZ',
 '000700.SZ',
 '000735.SZ',
 '002323.SZ',
 '002516.SZ',
 '002175.SZ',
 '002201.SZ',
 '002463.SZ',
 '002536.SZ',
 '002012.SZ',
 '002899.SZ',
 '000564.SZ',
 '000881.SZ',
 '002348.SZ',
 '002474.SZ',
 '002436.SZ',
 '300077.SZ',
 '000815.SZ',
 '002478.SZ',
 '000557.SZ',
 '002206.SZ',
 '300343.SZ']

In [25]:
cols = ['date', 'code', 'time', 'Last', 'volume', 'bid_size1', 'bid1']
data_filter[cols]

,date,code,time,Last,volume,bid_size1,bid1
383472,2024-02-19,603660.SH,0 days 09:25:03,5.39,979500.0,-15523973,5.39
383473,2024-02-19,603660.SH,0 days 09:25:18,5.39,0.0,-15523973,5.39
383474,2024-02-19,603660.SH,0 days 09:25:48,5.39,0.0,-15523973,5.39
383475,2024-02-19,603660.SH,0 days 09:26:18,5.39,0.0,-15523973,5.39
383476,2024-02-19,603660.SH,0 days 09:26:48,5.39,0.0,-15523973,5.39
...,...,...,...,...,...,...,...
21882664,2024-02-19,002659.SZ,0 days 10:37:48,3.38,0.0,-21443673,3.38
21882665,2024-02-19,002659.SZ,0 days 10:37:57,3.38,0.0,-21443573,3.38
21882666,2024-02-19,002659.SZ,0 days 10:38:00,3.38,26600.0,-21470173,3.38
21882667,2024-02-19,002659.SZ,0 days 10:38:03,3.38,0.0,-21470173,3.38
21882668,2024-02-19,002659.SZ,0 days 10:38:09,3.38,0.0,-21469673,3.38

In [36]:
data[(data['code'] == '600151.SH') & (data['time'] > '09:38:00')][cols].head(100)

              date       code            time  Last    volume  bid_size1  bid1
2904352 2024-02-19  600151.SH 0 days 09:38:02  4.85       0.0     101300  4.85
2904353 2024-02-19  600151.SH 0 days 09:38:05  4.85   46200.0      54700  4.85
2904354 2024-02-19  600151.SH 0 days 09:38:08  4.85   78200.0      12800  4.84
2904355 2024-02-19  600151.SH 0 days 09:38:11  4.84    1900.0      17500  4.84
2904356 2024-02-19  600151.SH 0 days 09:38:14  4.84   17200.0       7000  4.84
2904357 2024-02-19  600151.SH 0 days 09:38:17  4.84     800.0      29200  4.84
2904358 2024-02-19  600151.SH 0 days 09:38:20  4.84    6400.0      24000  4.84
2904359 2024-02-19  600151.SH 0 days 09:38:23  4.84    1100.0      28900  4.84
2904360 2024-02-19  600151.SH 0 days 09:38:26  4.84   10000.0      16900  4.84
2904361 2024-02-19  600151.SH 0 days 09:38:29  4.83   20500.0      57500  4.83
2904362 2024-02-19  600151.SH 0 days 09:38:32  4.83    7800.0      52900  4.83
2904363 2024-02-19  600151.SH 0 days 09:38:35  4.83    2600.0      53300  4.83
2904364 2024-02-19  600151.SH 0 days 09:38:38  4.83    6000.0      51100  4.83
2904365 2024-02-19  600151.SH 0 days 09:38:41  4.83    3900.0      54800  4.83
2904366 2024-02-19  600151.SH 0 days 09:38:44  4.84   11300.0      48500  4.83
2904367 2024-02-19  600151.SH 0 days 09:38:47  4.83   52800.0       4200  4.83
2904368 2024-02-19  600151.SH 0 days 09:38:50  4.84   31200.0      38400  4.83
2904369 2024-02-19  600151.SH 0 days 09:38:53  4.84   12200.0      38900  4.83
2904370 2024-02-19  600151.SH 0 days 09:38:56  4.84    6800.0      42200  4.83
2904371 2024-02-19  600151.SH 0 days 09:38:59  4.84   17500.0     108500  4.83
2904372 2024-02-19  600151.SH 0 days 09:39:02  4.84   13100.0     103500  4.83
2904373 2024-02-19  600151.SH 0 days 09:39:05  4.83    5400.0     101300  4.83
2904374 2024-02-19  600151.SH 0 days 09:39:08  4.83    2300.0     101800  4.83
2904375 2024-02-19  600151.SH 0 days 09:39:11  4.83       0.0     103400  4.83
2904376 2024-02-19  600151.SH 0 days 09:39:14  4.84   29800.0      73800  4.83
2904377 2024-02-19  600151.SH 0 days 09:39:17  4.83    5600.0      70900  4.83
2904378 2024-02-19  600151.SH 0 days 09:39:20  4.83   15000.0      65900  4.83
2904379 2024-02-19  600151.SH 0 days 09:39:23  4.83   54200.0      13300  4.83
2904380 2024-02-19  600151.SH 0 days 09:39:26  4.82   15200.0     115400  4.82
2904381 2024-02-19  600151.SH 0 days 09:39:29  4.82   30700.0     105300  4.82
2904382 2024-02-19  600151.SH 0 days 09:39:32  4.83    1500.0     105400  4.82
2904383 2024-02-19  600151.SH 0 days 09:39:35  4.83   23247.0       1353  4.83
2904384 2024-02-19  600151.SH 0 days 09:39:38  4.82   60300.0       1600  4.83
2904385 2024-02-19  600151.SH 0 days 09:39:41  4.83    9300.0       4400  4.83
2904386 2024-02-19  600151.SH 0 days 09:39:44  4.83    5800.0      69253  4.82
2904387 2024-02-19  600151.SH 0 days 09:39:47  4.83    1400.0      70753  4.82
2904388 2024-02-19  600151.SH 0 days 09:39:50  4.82    6900.0      68253  4.82
2904389 2024-02-19  600151.SH 0 days 09:39:53  4.81   75653.0      33100  4.81
2904390 2024-02-19  600151.SH 0 days 09:39:56  4.82   10200.0      32400  4.81
2904391 2024-02-19  600151.SH 0 days 09:39:59  4.82     200.0      35500  4.81
2904392 2024-02-19  600151.SH 0 days 09:40:02  4.82  141600.0       8200  4.82
2904393 2024-02-19  600151.SH 0 days 09:40:05  4.82       0.0        100  4.83
2904394 2024-02-19  600151.SH 0 days 09:40:08  4.83    9700.0       2600  4.83
2904395 2024-02-19  600151.SH 0 days 09:40:11  4.81   89700.0       8500  4.81
2904396 2024-02-19  600151.SH 0 days 09:40:14  4.82   18600.0        300  4.82
2904397 2024-02-19  600151.SH 0 days 09:40:17  4.81   19400.0        500  4.82
2904398 2024-02-19  600151.SH 0 days 09:40:20  4.82    1100.0      38200  4.81
2904399 2024-02-19  600151.SH 0 days 09:40:23  4.82    3500.0       4200  4.82
2904400 2024-02-19  600151.SH 0 days 09:40:26  4.83   16700.0       8400  4.83
2904401 2024-02-19  600151.SH 0 days 09:40:29  4.83     100.0       4100  4.83
2904402 2024-02-19  600151.SH 0 days 09:40:32  4.84    2800.0       5000  4.83
2904403 2024-02-19  600151.SH 0 days 09:40:35  4.84   22300.0       6700  4.83
2904404 2024-02-19  600151.SH 0 days 09:40:38  4.83     600.0       5400  4.83
2904405 2024-02-19  600151.SH 0 days 09:40:41  4.84   11200.0      40800  4.84
2904406 2024-02-19  600151.SH 0 days 09:40:44  4.84   11400.0      30700  4.84
2904407 2024-02-19  600151.SH 0 days 09:40:47  4.85   16500.0      33300  4.84
2904408 2024-02-19  600151.SH 0 days 09:40:50  4.85   13300.0       2800  4.85
2904409 2024-02-19  600151.SH 0 days 09:40:53  4.86    3800.0      12600  4.85
2904410 2024-02-19  600151.SH 0 days 09:40:56  4.86   14100.0        200  4.85
2904411 2024-02-19  600151.SH 0 days 09:40:59  4.86    1200.0       2800  4.85
2904412 2024-02-19  600151.SH 0 days 09:41:02  4.86    3600.0      23000  4.85
2904413 2024-02-19  600151.SH 0 days 09:41:05  4.86    1900.0      23000  4.85
2904414 2024-02-19  600151.SH 0 days 09:41:08  4.87   35700.0       5700  4.86
2904415 2024-02-19  600151.SH 0 days 09:41:11  4.87    7100.0       6500  4.86
2904416 2024-02-19  600151.SH 0 days 09:41:14  4.85   20100.0      18000  4.85
2904417 2024-02-19  600151.SH 0 days 09:41:17  4.87    3100.0       6600  4.86
2904418 2024-02-19  600151.SH 0 days 09:41:20  4.86    8053.0      47900  4.86
2904419 2024-02-19  600151.SH 0 days 09:41:23  4.86     100.0      51800  4.86
2904420 2024-02-19  600151.SH 0 days 09:41:26  4.90    9200.0       4800  4.87
2904421 2024-02-19  600151.SH 0 days 09:41:29  4.90       0.0       6200  4.87
2904422 2024-02-19  600151.SH 0 days 09:41:32  4.90       0.0      42500  4.88
2904423 2024-02-19  600151.SH 0 days 09:41:35  4.89    2800.0        900  4.89
2904424 2024-02-19  600151.SH 0 days 09:41:38  4.90   27800.0       6300  4.89
2904425 2024-02-19  600151.SH 0 days 09:41:41  4.90   13300.0       6200  4.89
2904426 2024-02-19  600151.SH 0 days 09:41:44  4.90    4000.0      10100  4.89
2904427 2024-02-19  600151.SH 0 days 09:41:47  4.89   11300.0        500  4.89
2904428 2024-02-19  600151.SH 0 days 09:41:50  4.90    2900.0       5400  4.88
2904429 2024-02-19  600151.SH 0 days 09:41:53  4.90    8800.0       5600  4.88
2904430 2024-02-19  600151.SH 0 days 09:41:56  4.89    2000.0       7300  4.88
2904431 2024-02-19  600151.SH 0 days 09:41:59  4.89    6600.0       7900  4.88
2904432 2024-02-19  600151.SH 0 days 09:42:02  4.89    4400.0      15200  4.88
2904433 2024-02-19  600151.SH 0 days 09:42:05  4.90    3800.0      15200  4.88
2904434 2024-02-19  600151.SH 0 days 09:42:08  4.89   14200.0       2900  4.89
2904435 2024-02-19  600151.SH 0 days 09:42:11  4.89    3600.0       1600  4.89
2904436 2024-02-19  600151.SH 0 days 09:42:14  4.90    3500.0       3100  4.89
2904437 2024-02-19  600151.SH 0 days 09:42:17  4.90     400.0       3900  4.89
2904438 2024-02-19  600151.SH 0 days 09:42:20  4.89    3000.0       3200  4.89
2904439 2024-02-19  600151.SH 0 days 09:42:23  4.89    2500.0       5900  4.89
2904440 2024-02-19  600151.SH 0 days 09:42:26  4.89   17300.0      14800  4.88
2904441 2024-02-19  600151.SH 0 days 09:42:29  4.90    3200.0        700  4.89
2904442 2024-02-19  600151.SH 0 days 09:42:32  4.90    7200.0        400  4.89
2904443 2024-02-19  600151.SH 0 days 09:42:35  4.89    6000.0       2100  4.89
2904444 2024-02-19  600151.SH 0 days 09:42:38  4.90   11500.0       9300  4.88
2904445 2024-02-19  600151.SH 0 days 09:42:41  4.90    4900.0       9900  4.88
2904446 2024-02-19  600151.SH 0 days 09:42:44  4.88    1200.0       9700  4.88
2904447 2024-02-19  600151.SH 0 days 09:42:47  4.88    4800.0       9800  4.88
2904448 2024-02-19  600151.SH 0 days 09:42:50  4.88   23100.0      12700  4.86
2904449 2024-02-19  600151.SH 0 days 09:42:53  4.88    4900.0       5700  4.87
2904450 2024-02-19  600151.SH 0 days 09:42:56  4.87     100.0       5600  4.87
2904451 2024-02-19  600151.SH 0 days 09:42:59  4.88    1600.0       6600  4.87